"""try artist upcoming_shows

Revision ID: 337877ac6ac8
Revises: c7cb439e7eef
Create Date: 2020-05-16 20:57:16.456003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337877ac6ac8'
down_revision = 'c7cb439e7eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'num_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('num_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
