"""venue-descriontion-to-venue-seeking-description

Revision ID: c6edadeeebee
Revises: 337877ac6ac8
Create Date: 2020-05-17 17:34:25.946049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6edadeeebee'
down_revision = '337877ac6ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('show_venue_id_fkey', 'show', type_='foreignkey')
    op.drop_constraint('show_artist_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'], ondelete='cascade')
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=1024), nullable=True))
    op.drop_column('venue', 'num_shows')
    op.drop_column('venue', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('num_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_description')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_artist_id_fkey', 'show', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key('show_venue_id_fkey', 'show', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
