"""add artist_num_show

Revision ID: c7cb439e7eef
Revises: d4f242dd1535
Create Date: 2020-05-16 16:23:34.763797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cb439e7eef'
down_revision = 'd4f242dd1535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('num_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'num_shows')
    # ### end Alembic commands ###
